matrix:
  include:
  - os: linux
    language: generic
    env: PY=3.6
  - os: osx
    language: generic
    env: PY=3.6
branches:
  only:
  - master
  - ESS_GUI
addons:
  apt:
    packages:
    - python-pyopencl
    - ocl-icd-opencl-dev
    - opencl-headers
    - libblas-dev
    - libatlas-dev
    - libatlas-base-dev
    - liblapack-dev
    - gfortran
    - libhdf5-serial-dev
before_install:
- echo $TRAVIS_OS_NAME
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
  -O miniconda.sh; elif
  [[ "$TRAVIS_OS_NAME" == "osx" ]]; then wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh
  -O miniconda.sh; fi
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
#- conda update --yes conda
- conda info -a
- conda install --yes python=$PY numpy scipy cython pylint wxpython matplotlib lxml h5py sphinx pyparsing html5lib reportlab pybind11 appdirs six numba mako
install:
# Make sure libOpenCL is available to miniconda on linux.
- pip install periodictable xhtml2pdf unittest-xml-reporting pylint
#- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ln -s /usr/lib/x86_64-linux-gnu/libOpenCL.so* $HOME/miniconda/lib; ls -l $HOME/miniconda/lib; fi
#- if test -n "$TRAVIS_OS_NAME" == "linux"; then pip install pyopencl; fi
# Install pyopencl, but quietly ignore failures
- pip install pyopencl || true
script:
- cd ..
- export WORKSPACE=$(pwd)
- git clone --depth=50 --branch=master https://github.com/SasView/sasmodels.git sasmodels
- git clone --depth=50 --branch=master https://github.com/bumps/bumps.git
- ls -ltr
- if [ ! -d "utils" ]; then mkdir utils; fi
- /bin/sh -xe sasview/build_tools/travis_build.sh
- export LC_ALL=en_US.UTF-8
- export LANG=en_US.UTF-8
notifications:
  slack:
    secure: TlsEpZiMLmOOgnmdG0I/oB4tq3bbQYeBBQi6S5qLlkYE9EjUTbbfg7oz0JYUsQ56FAsdFR8zswpBsX7PebZerzrq0ZmvfHSiJhOFIdBfY5Nb7bmLW8/9pUNWV57ON/8Gw2fE5ytc7FgvCGR64yb2QISI/150SIUwvdL5HXTxRWI=
