name: qt5_win
channels:
  - conda-forge
dependencies:
 - alabaster
 - colorama
 - ipykernel
 - ipython
 - jupyter
 - nbformat
 - pyopencl
 - scipy
 - hdf5
 - h5py
 - lxml
 - twisted
 - sphinx
 - pytest
 - cython
 - sip
 - numba
 - setuptools
 - numpy
 - qtconsole
 - mkl
 - pip:
   - matplotlib
   - bumps
   - pyinstaller
   - periodictable
   - xhtml2pdf
   - ../../../PyQt5_commercial-5.12.2-5.12.3-cp35.cp36.cp37.cp38-none-win_amd64.whl
   - qt5reactor
   - tinycc
