name: nightly-build

#TODO: will be changed to cronjob
on:
  [push, pull_request]

defaults:
  run:
    shell: bash

jobs:
  nightly-build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/download-artifact@v3

    - name: List lables in PR
      run: |
      x=${{ toJson(github.event.pull_request.labels.*.name) }}
      echo $x


#TODO: Check what is the structure of downloaded files and update
#    - name: Upload installer to GitHub releases
#        if: ${{ matrix.installer }}
#        uses: ncipollo/release-action@v1
#        with:
#          draft: false
#          prerelease: true
#          allowUpdates: true
#          replacesArtifacts: true
#          token: ${{ secrets.GITHUB_TOKEN }}
#          artifacts: "SasView5.dmg, setupSasView.exe, sasview5.tar.gz"
#          body: "Nightly build for SasView"
#          name: "nightly-build"
#          tag: "nightly-build"