name: Last Succesful Build
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  nightly:
    name: Deploy nightly
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    runs-on: ${{ matrix.os }}
    steps:

    - name: Find matching workflow
      uses: SamhammerAG/last-successful-build-action@v2
      with:
          branch: "main"
          workflow: "Installer"
          verify: true


